--
-- Addon       _mano_db_puzzles_cairns.lua
-- Author      marcob@marcob.org
-- StartDate   29/05/2018
--
-- Expansion:  Mathosia
-- Source:     http://www.kfguides.com/rift/puzzlesguide.php
-- Credits:    Krinadon and Faiona, or KFGuides (Support@KFGuides.com)
--
-- Expansion:  Storm Legion - Cairns
-- Source:     http://archive.riftscene.com/guides/achievements/cairn-do-too-storm-legion-cairns/
-- Credits:    Cupcakes
--
-- Data:       Storm Legion - Puzzles
-- Source:     http://tmrguides.blogspot.com/
--
-- Format:     {
--                label="puzzle/cairn name",
--                location="zone Name",
--                location=["es.: Lake of Solace"],
--                x=nn,
--                z=nn,
--                y=[nn],
--                text=["...mi favourite fishing spot..."]
--             }
--
--             ONLY fields between [] may be missing.
--
-- t  =  {  idx         =  newnote.idx or self.lastidx,
--          label       =  newnote.label,
--          text        =  newnote.text,
--          category    =  newnote.category,
--          playerpos   =  playerpos,
--                         x              =  tbl.x or nil,
--                         z              =  tbl.z,
--                         y              =  tbl.y
--                         locationName   =  tbl.location or nil,
--                         name           =  "forums",
--                         radius         =  self.default.radius,
--                         zoneid         =  tbl.zoneid or  self.extdbhandler.zonename2id[zonename],
--                         zonename       =  zonename,
--                         },
--          timestamp   =  newnote.timestamp or os.time(),
--       }
--
--
-- local addon, mano = ...

function __externaldbs()
   -- the new instance
   local self =   {
                     id2zn =  {},
                     zn2id =  {},
                     db	   =  {},
                  }
      -- public fields go in the instance table

   self.zn2id  =  {  ["Meridian"]               =  'z6BA3E574E9564149',
                     ["Morban"]                 =  'z39095BA75AD7DC03',
                     ["Silverwood"]             =  'z0000000CB7B53FD7',
                     ["Gloamwood"]              =  'z0000001B2BB9E10E',
                     ["Scarlet Gorge"]          =  'z019595DB11E70F58',
                     ["Freemarch"]              =  'z00000013CAF21BE3',
                     ["Stonefield"]             =  'z585230E5F68EA919',
                     ["Scarwood Reach"]         =  'z000000142C649218',
                     ["Droughtlands"]           =  'z1416248E485F6684',
                     ["Iron Pine Peak"]         =  'z00000016EB9ECBA5',
                     ["Shimmersand"]            =  'z000000069C1F0227',
                     ["Stillmoor"]              =  'z0000001A4AF8CD7A',
                     ["Ember Isle"]             =  'z76C88A5A51A38D90',
                     ["Ardent Domain"]          =  'z563CB77E4A32233F',
                     ["City Core"]              =  'z754553DD46F46371',
                     ["Eastern Holdings"]       =  'z48530386ED2EA5AD',
                     ["Seratos"]                =  'z59124F7DD7F15825',
                     ["Kingsward"]              =  'z4D8820D7EF52685C',
                     ["The Dendrome"]           =  'z10D7E74AB6D7B293',
                     ["Moonshade Highlands"]    =  'z0000001804F56C61',
                     ["Cape Jule"]              =  'z698CB7B72B3D69E9',
                     ["Ashora"]                 =  'z2F1E4708BEC6A608',
                     ["Kingdom of Pelladane"]   =  'z1C938C07F41C83CC',
                     ["Steppes of Infinity"]    =  'z2F9C9E1FF91F9293',
                  }

   self.id2zn  =  {  ['z6BA3E574E9564149']      =  "Meridian",
                     ['z39095BA75AD7DC03']      =  "Morban",
                     ['z0000000CB7B53FD7']      =  "Silverwood",
                     ['z0000001B2BB9E10E']      =  "Gloamwood",
                     ['z019595DB11E70F58']      =  "Scarlet Gorge",
                     ['z00000013CAF21BE3']      =  "Freemarch",
                     ['z585230E5F68EA919']      =  "Stonefield",
                     ['z000000142C649218']      =  "Scarwood Reach",
                     ['z1416248E485F6684']      =  "Droughtlands",
                     ['z00000016EB9ECBA5']      =  "Iron Pine Peak",
                     ['z000000069C1F0227']      =  "Shimmersand",
                     ['z0000001A4AF8CD7A']      =  "Stillmoor",
                     ['z76C88A5A51A38D90']      =  "Ember Isle",
                     ['z563CB77E4A32233F']      =  "Ardent Domain",
                     ['z754553DD46F46371']      =  "City Core",
                     ['z48530386ED2EA5AD']      =  "Eastern Holdings",
                     ['z59124F7DD7F15825']      =  "Seratos",
                     ['z4D8820D7EF52685C']      =  "Kingsward",
                     ['z10D7E74AB6D7B293']      =  "The Dendrome",
                     ['z0000001804F56C61']      =  "Moonshade Highlands",
                     ['z698CB7B72B3D69E9']      =  "Cape Jule",
                     ['z2F1E4708BEC6A608']      =  "Ashora",
                     ['z1C938C07F41C83CC']      =  "Kingdom of Pelladane",
                     ['z2F9C9E1FF91F9293']      =  "Steppes of Infinity",
                  }


-- t  =  {  idx         =  newnote.idx or self.lastidx,
--          label       =  newnote.label,
--          text        =  newnote.text,
--          category    =  newnote.category,
--          playerpos   =  y         =  tbl.y or nil,
--                         x         =  tbl.x,
--                         z         =  tbl.z,
--                         locationName   =  tbl.location or nil,
--                         name           =  "forums",
--                         radius         =  self.default.radius,
--                         zoneid         =  tbl.zoneid or  self.extdbhandler.zonename2id[zonename],
--                         zonename       =  zonename,
--                         },
--          timestamp   =  newnote.timestamp or os.time(),
--       }


  t   =  {  ["Silverwood"]       =  {  idx         =  nil,
                                       text        =  nil,
                                       label       =  "Puzzled at the Top of the World",
                                       category    =  "Puzzles",
                                       playerpos   =  {  y        =  0,
                                                         x        =  6515,
                                                         z        =  3080,
                                                         zonename =  "Silverwood",
                                                         zoneid   =  self.zn2id["Silverwood"],
                                                      },
                                       timestamp   =  os.time(),
                                    },   -- 1
            ["Gloamwood"]        =  {  idx         =  nil,
                                       text        =  nil,
                                       label       =  "Shield Wall",
                                       category    =  "Puzzles",
                                       playerpos   =  {  y        =  0,
                                                         x        =  4540,
                                                         z	      =  2382,
                                                         zonename =  "Gloamwood",
                                                         zoneid   =  self.zn2id["Gloamwood"],
                                                      },
                                       timestamp   =  os.time(),
                                    },   -- 2
            ["Scarlet Gorge"]    =  {  idx         =  nil,
                                       text        =  nil,
                                       label       =  "A Barrel of Laughs",
                                       category    =  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=3619,
                                                         z=2775
                                                         zonename =  "Scarlet Gorge",
                                                         zoneid   =  self.zn2id["Scarlet Gorge"],
                                                      },
                                       timestamp   =  os.time(),
                                    },   -- 3
            ["Freemarch"]        =  {  idx         =  nil,
                                       text        =  nil,
                                       label       =  "Lake Solace",
                                       category    =  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=5998,
                                                         z=6141
                                                         zonename =  "Freemarch",
                                                         zoneid   =  self.zn2id["Freemarch"],
                                       },
                                       timestamp   =  os.time(),
                                    },   -- 4


            ["Stonefield"]       =  {  idx         =  nil,
                                       text        =  nil,
                                       label       =  "Spinning Plates",
                                       category    =  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=4577,
                                                         z=4974
                                                         zonename =  "Stonefield",
                                                         zoneid   =  self.zn2id["Stonefield"],
                                                      },
                                       timestamp   =  os.time(),
                                    },   -- 5
            ["Scarwood Reach"]   =  {  idx         =  nil,
                                       text        =  nil,
                                       label       =  "Scarwood by Torchlight",
                                       category    =  "Puzzles",
                                       playerpos   =  {  y  =  0,
                                                         x  =  3123,
                                                         z  =  4426,
                                                         zonename =  "Scarwood Reach",
                                                         zoneid   =  self.zn2id["Scarwood Reach"],
                                       },
                                       timestamp   =  os.time(),
                                    },   -- 6
            ["Droughtlands"]     =  {  idx         =  nil,
                                       text        =  nil,
                                       label       =  "Don’t be Cagey",
                                       category    =  "Puzzles",
                                       playerpos   =  {  y  =  0,
                                                         x  =  8335,
                                                         z  =  6200
                                                         zonename =  "Droughtlands",
                                                         zoneid   =  self.zn2id["Droughtlands"],
                                       },
                                       timestamp   =  os.time(),
                                    },   -- 7
            ["Iron Pine Peak"]   =  {  idx         =  nil,
                                       text        =  nil,
                                       label       =  "Tracks in the Snow",
                                       category    =  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=3760,
                                                         z=2266,
                                                         zonename =  "Iron Pine Peak",
                                                         zoneid   =  self.zn2id["Iron Pine Peak"],
                                                      },
                                       timestamp   =  os.time(),
                                    },   -- 8
            ["Shimmersand"]      =  {  idx         =  nil,
                                       text        =  nil,
                                       label       =  "The Peg Solitaire",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y  =  0,
                                                         x  =  6414,
                                                         z  =  7714
                                                         zonename =  "Shimmersand",
                                                         zoneid   =  self.zn2id["Shimmersand"],
                                                      },
                                       timestamp   =  os.time(),
                                    },   -- 9
            ["Stillmoor"]        =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label			=  "Herding Bats",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y  =  0,
                                                         x  =  1705,
                                                         z  =  2310
                                                         zonename =  "Shimmersand",
                                                         zoneid   =  self.zn2id["Shimmersand"],
                                                      },
                                    },   -- 10
            ["Ember Isle"]       =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label			=  "Emerald Enigma",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y  =  0,
                                                         x  =  12823,
                                                         z  =  3857,
                                                         zonename =  "Ember Isle",
                                                         zoneid   =  self.zn2id["Ember Isle"],
                                                      },
                                    },   -- 11
            ["Ardent Domain"]    =  {  idx         =  nil,
                                       text        =  "Artifact Set Required: Circuit Diagrams (12)",
                                       timestamp   =  os.time(),
                                       label			=  "Circuit Diagrams",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=5988,
                                                         z=10744,
                                                         zonename =  "Ardent Domain",
                                                         zoneid   =  self.zn2id["Ardent Domain"],
                                                      },
                                    },                              -- 12
            ["City Core"]        =  {  idx         =  nil,
                                       text        =  "Artifact Set Required: A Knight's Tour (6)",
                                       timestamp   =  os.time(),
                                       label			=  "A Knight's Tour",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=6984,
                                                         z=10036,
                                                         zonename =  "City Core",
                                                         zoneid   =  self.zn2id["City Core"],
                                                      },
                                    },                              -- 13
            ["Eastern Holdings"] =  {  idx         =  nil,
                                       text        =  "Artifact Set Required: M'doidoi Dolls (9) (bottom of the pond has a portal)",
                                       timestamp   =  os.time(),
                                       label			=  "M'doidoi Dolls",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=8800,
                                                         z=8750,
                                                         zonename =  "Eastern Holdings",
                                                         zoneid   =  self.zn2id["Eastern Holdings"],
                                                      },
                                    },	     -- 14
            ["Seratos"]          =  {  idx         =  nil,
                                       text        =  "Artifact Set Required: Seeing Dots, 3 Blob of Ectoplasm (found in NW Ardent Domain)",
                                       timestamp   =  os.time(),
                                       label			=  "Seeing Dots",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=11400,
                                                         z=6280,
                                                         zonename =  "Seratos",
                                                         zoneid   =  self.zn2id["Seratos"],
                                                      },
                                    },	                     -- 15
            ["Kingsward"]        =  {  idx         =  nil,
                                       text        =  "Artifact Set Required: Queen's Gambit (12)",
                                       timestamp   =  os.time(),
                                       label			=  "Queen's Gambit",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=4813,
                                                         z=8675,
                                                         zonename =  "Kingsward",
                                                         zoneid   =  self.zn2id["Kingsward"],
                                                      },
                                    },
            ["Morban"]           =  {  idx         =  nil,
                                       text        =  "Artifact Set Required: Black Box",
                                       timestamp   =  os.time(),
                                       label			=  "Black Box",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=12700,
                                                         z=7450,
                                                         zonename =  "Morban",
                                                         zoneid   =  self.zn2id["Morban"],
                                                      },

                                    }, -- 16
            ["The Dendrome"]     =  {  idx         =  nil,
                                       text        =  "Artifact Set Required: Snake Eyes, 10 Glowing Rootballs (attained from watching puppet shows in Hailol)",
                                       timestamp   =  os.time(),
                                       label			=  "Snake Eyes",
                                       category		=  "Puzzles",
                                       playerpos   =  {  y=0,
                                                         x=4410,
                                                         z=4240,
                                                         zonename =  "Morban",
                                                         zoneid   =  self.zn2id["Morban"],
                                                      },
                                    }, -- 17
         }

self.db.puzzles   =  t
t                 =  {}

t   =  {    ["Freemarch"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Discarded Strongbox",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  5626,
                                                            z  =  5685,
                                                            zonename =  "Freemarch",
                                                            zoneid   =  self.zn2id["Freemarch"],
                                                         },
                                       },   -- 18
            ["Freemarch"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Forgotten Casket",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  5449,
                                                            z  =  6009,
                                                            zonename =  "Freemarch",
                                                            zoneid   =  self.zn2id["Freemarch"],
                                                         },
                                       },   -- 19
            ["Freemarch"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Plundered Safe",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  5560,
                                                            z  =  6233,
                                                            zonename =  "Freemarch",
                                                            zoneid   =  self.zn2id["Freemarch"],
                                                         },
                                       },   -- 20
            ["Freemarch"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Lost Soul",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  5872,
                                                            z  =  6223,
                                                            zonename =  "Freemarch",
                                                            zoneid   =  self.zn2id["Freemarch"],
                                                         },
                                       },   -- 21
            ["Freemarch"]           =  {  idx         =  nil,
                                          text        =  "DO THIS ONE LAST!"
                                          timestamp   =  os.time(),
                                          label       =  "Weed Covered Vase",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  6029,
                                                            z  =  6509,
                                                            zonename =  "Freemarch",
                                                            zoneid   =  self.zn2id["Freemarch"],
                                                         },
                                       }, -- 22
            ["Freemarch"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Heavy Metal Barrel",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  6311,
                                                            z  =  6228
                                                            zonename =  "Freemarch",
                                                            zoneid   =  self.zn2id["Freemarch"],
                                                         },
                                       },   -- 23
            ["Freemarch"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Sunken Cargo",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  6708,
                                                            z  =  5987,
                                                            zonename =  "Freemarch",
                                                            zoneid   =  self.zn2id["Freemarch"],
                                                         },
                                       },   -- 24
            ["Freemarch"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Old Chest",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  6430,
                                                            z  =  6430,
                                                            zonename =  "Freemarch",
                                                            zoneid   =  self.zn2id["Freemarch"],
                                                         },
                                       },   -- 25
            ["Stonefied"]           =  {  idx         =  nil,
                                          text        =  "This is considered a Freemarch Cairn. It caps at Level 30"
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Bahar Farwind",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  5898,
                                                            z  =  5033,
                                                            zonename =  "Stonefied",
                                                            zoneid   =  self.zn2id["Stonefied"],
                                                         },
                                       },                                                                                                     -- 26
            ["Stonefied"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Nasreen Tahleed",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  5327,
                                                            z  =  5364,
                                                            zonename =  "Stonefied",
                                                            zoneid   =  self.zn2id["Stonefied"],
                                                         },
                                       },   -- 27
            ["Stonefied"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Valta Cliftswind",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  4664,
                                                            z  =  5006,
                                                            zonename =  "Stonefied",
                                                            zoneid   =  self.zn2id["Stonefied"],
                                                         },
                                       },   -- 28
            ["Glomwood"]            =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Nylaan Starhearth",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  5576,
                                                            z  =  3210,
                                                            zonename =  "Glomwood",
                                                            zoneid   =  self.zn2id["Glomwood"],
                                                         },
                                       },   -- 29
            ["Scarlet Gorge"]       =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Faraz Massi",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  4654,
                                                            z  =  3097,
                                                            zonename =  "Scarlet Gorge",
                                                            zoneid   =  self.zn2id["Scarlet Gorge"],
                                                         },
                                       },   -- 30
            ["Scarwood Reach"]      =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Engel Malik",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  4075,
                                                            z  =  4443,
                                                            zonename =  "Scarwood Reach",
                                                            zoneid   =  self.zn2id["Scarwood Reach"],
                                                         },
                                       },   -- 31
            ["Moonshade Highlands"] =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Roma Ga",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  5348,
                                                            z  =  2239,
                                                            zonename =  "Moonshade Highlands",
                                                            zoneid   =  self.zn2id["Moonshade Highlands"],
                                                         },
                                       },   -- 32
            ["Droughtlands"]        =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Mongo Vachir",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  9161,
                                                            z  =  6927,
                                                            zonename =  "Droughtlands",
                                                            zoneid   =  self.zn2id["Droughtlands"],
                                                         },
                                       },   -- 33
            ["Iron Pine Peak"]      =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Harwin Kalmar",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  4980,
                                                            z  =  1865,
                                                            zonename =  "Iron Pine Peak",
                                                            zoneid   =  self.zn2id["Iron Pine Peak"],
                                                         },
                                       },   -- 34
            ["Shimmersand"]         =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Qara Chuluun",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  7535,
                                                            z  =  7170,
                                                            zonename =  "Shimmersand",
                                                            zoneid   =  self.zn2id["Shimmersand"],
                                                         },
                                       },   -- 35
            ["Stillmoor"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Cairn of Thera Valnir",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  1585,
                                                            z  =  1862,
                                                            zonename =  "Stillmoor",
                                                            zoneid   =  self.zn2id["Stillmoor"],
                                                         },
                                       },   -- 36
            ["Cape Jule"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Ina'eme Sarus",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  7438,
                                                            z  =  12194,
                                                            zonename =  "Cape Jule",
                                                            zoneid   =  self.zn2id["Cape Jule"],
                                                         },
                                       },  -- 37
            ["Cape Jule"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Queny Sulgar",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  7765,
                                                            z  =  11041,
                                                            zonename =  "Cape Jule",
                                                            zoneid   =  self.zn2id["Cape Jule"],
                                                         },
                                       },  -- 38
            ["Cape Jule"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Asha Tonavar",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  6436,
                                                            z  =  11015,
                                                            zonename =  "Cape Jule",
                                                            zoneid   =  self.zn2id["Cape Jule"],
                                                         },
                                       },  -- 39
            ["City Core"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Nunmemph Batshinshi",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  7266,
                                                            z  =  9340,
                                                            zonename =  "City Core",
                                                            zoneid   =  self.zn2id["City Core"],
                                                         },
                                       },   -- 40
            ["City Core"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Warsul Icero",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  7096,
                                                            z  =  8585,
                                                            zonename =  "City Core",
                                                            zoneid   =  self.zn2id["City Core"],
                                                         },
                                       },   -- 41
            ["City Core"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Irque Guemech",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  7168,
                                                            z  =  8303,
                                                            zonename =  "City Core",
                                                            zoneid   =  self.zn2id["City Core"],
                                                         },
                                       },   -- 42
            ["Eastern Holdings"]    =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Oryp Namap",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  7534,
                                                            z  =  8879,
                                                            zonename =  "Eastern Holdings",
                                                            zoneid   =  self.zn2id["Eastern Holdings"],
                                                         },
                                       },   -- 43
            ["Eastern Holdings"]    =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Tathon I'rilgar",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  8090,
                                                            z  =  9626,
                                                            zonename =  "Eastern Holdings",
                                                            zoneid   =  self.zn2id["Eastern Holdings"],
                                                         },
                                       },   -- 44
            ["Eastern Holdings"]    =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Banald Warver",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  9096,
                                                            z  =  8384,
                                                            zonename =  "Eastern Holdings",
                                                            zoneid   =  self.zn2id["Eastern Holdings"],
                                                         },
                                       },   -- 45
            ["Ardent Domain"]       =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Yer'shyi Att",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y  =  0,
                                                            x  =  5844,
                                                            z  =  9834,
                                                            zonename =  "Ardent Domain",
                                                            zoneid   =  self.zn2id["Ardent Domain"],
                                                         },
                                       },   -- 46
            ["Ardent Domain"]       =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Riduf Enthurn",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  4830,
                                                            z  =  10189,
                                                            zonename =  "Ardent Domain",
                                                            zoneid   =  self.zn2id["Ardent Domain"],
                                                         },
                                       },  -- 47
            ["Kingsward"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Niey Tiran",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  6231,
                                                            z  =  7240,
                                                            zonename =  "Kingsward",
                                                            zoneid   =  self.zn2id["Kingsward"],
                                                         },
                                       },   -- 48
            ["Kingsward"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Isbur Oughverund",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  5601,
                                                            z  =  8070,
                                                            zonename =  "Kingsward",
                                                            zoneid   =  self.zn2id["Kingsward"],
                                                         },
                                       },   -- 49
            ["Kingsward"]           =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Skeltorard Perdyn",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  4066,
                                                            z  =  9072,
                                                            zonename =  "Kingsward",
                                                            zoneid   =  self.zn2id["Kingsward"],
                                                         },
                                       },   -- 50
            ["Ashora"]              =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Okalu Prev",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  4063,
                                                            z  =  7123,
                                                            zonename =  "Ashora",
                                                            zoneid   =  self.zn2id["Ashora"],
                                                         },
                                       },   -- 51
            ["Ashora"]              =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Omoosi Itnal",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  2678,
                                                            z  =  7117,
                                                            zonename =  "Ashora",
                                                            zoneid   =  self.zn2id["Ashora"],
                                                         },
                                       },   -- 52
            ["Ashora"]              =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Orn Tonall",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=  0,
                                                            x  =  2083,
                                                            z  =  6035,
                                                            zonename =  "Ashora",
                                                            zoneid   =  self.zn2id["Ashora"],
                                                         },
                                       },   -- 53
            ["The Dendrome"]        =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Morbur Atl Itther",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  2960,
                                                            z  =  4555,
                                                            zonename =  "The Dendrome",
                                                            zoneid   =  self.zn2id["The Dendrome"],
                                                         },
                                       },   -- 54
            ["The Dendrome"]        =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Uomu Tonig",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=  0,
                                                            x  =  3988,
                                                            z  =  5925,
                                                            zonename =  "The Dendrome",
                                                            zoneid   =  self.zn2id["The Dendrome"],
                                                         },
                                       },   -- 55
            ["The Dendrome"]        =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Ildbur Reled",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  4539,
                                                            z  =  4273,
                                                            zonename =  "The Dendrome",
                                                            zoneid   =  self.zn2id["The Dendrome"],
                                                         },
                                       },   -- 56
            ["Kingdom of Pelladane"]=  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Omight Tonig",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  8484,
                                                            z  =  5896,
                                                            zonename =  "Kingdom of Pelladane",
                                                            zoneid   =  self.zn2id["Kingdom of Pelladane"],
                                                         },
                                       },   -- 57
            ["Kingdom of Pelladane"]=  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Tirror Awaya",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  7455,
                                                            z  =  4077,
                                                            zonename =  "Kingdom of Pelladane",
                                                            zoneid   =  self.zn2id["Kingdom of Pelladane"],
                                                         },
                                       },   -- 58
            ["Seratos"]             =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Vesdar Doc",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  10593,
                                                            z  =  4800,
                                                            zonename =  "Kingdom of Pelladane",
                                                            zoneid   =  self.zn2id["Kingdom of Pelladane"],
                                                         },
                                       },   -- 59
            ["Seratos"]             =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Sayiss Vernys",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  11257,
                                                            z  =  3610,
                                                            zonename =  "Seratos",
                                                            zoneid   =  self.zn2id["Seratos"],
                                                         },
                                       },   -- 60
            ["Morban"]              =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Osm",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  12333,
                                                            z  =  4715,
                                                            zonename =  "Morban",
                                                            zoneid   =  self.zn2id["Morban"],
                                                         },
                                       },   -- 61
            ["Morban"]              =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Urari Urari",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  12641,
                                                            z  =  7346,
                                                            zonename =  "Morban",
                                                            zoneid   =  self.zn2id["Morban"],
                                                         },
                                       },   -- 62
            ["Morban"]              =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Lunibe",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  15702,
                                                            z  =  6066,
                                                            zonename =  "Morban",
                                                            zoneid   =  self.zn2id["Morban"],
                                                         },
                                       },   -- 63
            ["Steppes of Infinity"] =  {  idx         =  nil,
                                          text        =  nil,
                                          timestamp   =  os.time(),
                                          label       =  "Fevok Beleen",
                                          category	   =  "Cairns",
                                          playerpos   =  {  y	=   0,
                                                            x  =  15592,
                                                            z  =  7395,
                                                            zonename =  "Steppes of Infinity",
                                                            zoneid   =  self.zn2id["Steppes of Infinity"],
                                                         },
                                       },   -- 64
         }

   self.db.cairns =  t

   return self
end
