--
-- Addon       _puzzles.lua
-- Author      marcob@marcob.org
-- StartDate   29/05/2018
--
-- Expansion:  Storm Legion - Cairns
-- Source:     http://archive.riftscene.com/guides/achievements/cairn-do-too-storm-legion-cairns/
-- Credits:    Cupcakes
--
-- Format:
--
--
-- t  =  {  idx         =  newnote.idx or self.lastidx,
--          label       =  newnote.label,
--          text        =  newnote.text,
--          category    =  newnote.category,
--          playerpos   =  playerpos,
--                         x              =  tbl.x or nil,
--                         z              =  tbl.z,
--                         y              =  tbl.y
--                         locationName   =  tbl.location or nil,
--                         name           =  "forums",
--                         radius         =  self.default.radius,
--                         zoneid         =  tbl.zoneid or  self.extdbhandler.zonename2id[zonename],
--                         zonename       =  zonename,
--                         },
--          timestamp   =  newnote.timestamp or os.time(),
--       }
--
--
-- local addon, mano = ...

function __cairns()
   -- the new instance
   local self =   {
                  db =  {},
                  }
      -- public fields go in the instance table

   local zn2id =  {  ["Meridian"]               =  'z6BA3E574E9564149',
                     ["Morban"]                 =  'z39095BA75AD7DC03',
                     ["Silverwood"]             =  'z0000000CB7B53FD7',
                     ["Gloamwood"]              =  'z0000001B2BB9E10E',
                     ["Scarlet Gorge"]          =  'z019595DB11E70F58',
                     ["Freemarch"]              =  'z00000013CAF21BE3',
                     ["Stonefield"]             =  'z585230E5F68EA919',
                     ["Scarwood Reach"]         =  'z000000142C649218',
                     ["Droughtlands"]           =  'z1416248E485F6684',
                     ["Iron Pine Peak"]         =  'z00000016EB9ECBA5',
                     ["Shimmersand"]            =  'z000000069C1F0227',
                     ["Stillmoor"]              =  'z0000001A4AF8CD7A',
                     ["Ember Isle"]             =  'z76C88A5A51A38D90',
                     ["Ardent Domain"]          =  'z563CB77E4A32233F',
                     ["City Core"]              =  'z754553DD46F46371',
                     ["Eastern Holdings"]       =  'z48530386ED2EA5AD',
                     ["Seratos"]                =  'z59124F7DD7F15825',
                     ["Kingsward"]              =  'z4D8820D7EF52685C',
                     ["The Dendrome"]           =  'z10D7E74AB6D7B293',
                     ["Moonshade Highlands"]    =  'z0000001804F56C61',
                     ["Cape Jule"]              =  'z698CB7B72B3D69E9',
                     ["Ashora"]                 =  'z2F1E4708BEC6A608',
                     ["Kingdom of Pelladane"]   =  'z1C938C07F41C83CC',
                     ["Steppes of Infinity"]    =  'z2F9C9E1FF91F9293',
                  }

-- t  =  {  idx         =  newnote.idx or self.lastidx,
--          label       =  newnote.label,
--          text        =  newnote.text,
--          category    =  newnote.category,
--          playerpos   =  y         =  tbl.y or nil,
--                         x         =  tbl.x,
--                         z         =  tbl.z,
--                         locationName   =  tbl.location or nil,
--                         name           =  "forums",
--                         radius         =  self.default.radius,
--                         zoneid         =  tbl.zoneid or  self.extdbhandler.zonename2id[zonename],
--                         zonename       =  zonename,
--                         },
--          timestamp   =  newnote.timestamp or os.time(),
--       }

t  =  {}
t  =  {  ["Freemarch"]        =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Discarded Strongbox",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  5626,
                                                         z  =  5685,
                                                         zonename =  "Freemarch",
                                                         zoneid   =  zn2id["Freemarch"],
                                                      },
                                    },   -- 18
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Forgotten Casket",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  5449,
                                                         z  =  6009,
                                                         zonename =  "Freemarch",
                                                         zoneid   =  zn2id["Freemarch"],
                                                      },
                                    },   -- 19
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Plundered Safe",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  5560,
                                                         z  =  6233,
                                                         zonename =  "Freemarch",
                                                         zoneid   =  zn2id["Freemarch"],
                                                      },
                                    },   -- 20
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Lost Soul",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  5872,
                                                         z  =  6223,
                                                         zonename =  "Freemarch",
                                                         zoneid   =  zn2id["Freemarch"],
                                                      },
                                    },   -- 21
                                    {  idx         =  nil,
                                       text        =  "DO THIS ONE LAST!",
                                       timestamp   =  os.time(),
                                       label       =  "Weed Covered Vase",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  6029,
                                                         z  =  6509,
                                                         zonename =  "Freemarch",
                                                         zoneid   =  zn2id["Freemarch"],
                                                      },
                                    }, -- 22
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Heavy Metal Barrel",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  6311,
                                                         z  =  6228,
                                                         zonename =  "Freemarch",
                                                         zoneid   =  zn2id["Freemarch"],
                                                      },
                                    },   -- 23
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Sunken Cargo",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  6708,
                                                         z  =  5987,
                                                         zonename =  "Freemarch",
                                                         zoneid   =  zn2id["Freemarch"],
                                                      },
                                    },   -- 24
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Old Chest",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  6430,
                                                         z  =  6430,
                                                         zonename =  "Freemarch",
                                                         zoneid   =  zn2id["Freemarch"],
                                                      },
                                    },   -- 25
                                 },
         ["Stonefied"]        =  {  {  idx         =  nil,
                                       text        =  "This is considered a Freemarch Cairn. It caps at Level 30",
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Bahar Farwind",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  5898,
                                                         z  =  5033,
                                                         zonename =  "Stonefied",
                                                         zoneid   =  zn2id["Stonefied"],
                                                      },
                                    },                                                                                                     -- 26
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Nasreen Tahleed",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  5327,
                                                         z  =  5364,
                                                         zonename =  "Stonefied",
                                                         zoneid   =  zn2id["Stonefied"],
                                                      },
                                    },   -- 27
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Valta Cliftswind",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  4664,
                                                         z  =  5006,
                                                         zonename =  "Stonefied",
                                                         zoneid   =  zn2id["Stonefied"],
                                                      },
                                    },   -- 28
                                 },
         ["Glomwood"]            =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Nylaan Starhearth",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  5576,
                                                         z  =  3210,
                                                         zonename =  "Glomwood",
                                                         zoneid   =  zn2id["Glomwood"],
                                                      },
                                    },   -- 29
         ["Scarlet Gorge"]       =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Faraz Massi",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  4654,
                                                         z  =  3097,
                                                         zonename =  "Scarlet Gorge",
                                                         zoneid   =  zn2id["Scarlet Gorge"],
                                                      },
                                    },   -- 30
         ["Scarwood Reach"]      =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Engel Malik",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  4075,
                                                         z  =  4443,
                                                         zonename =  "Scarwood Reach",
                                                         zoneid   =  zn2id["Scarwood Reach"],
                                                      },
                                    },   -- 31
         ["Moonshade Highlands"] =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Roma Ga",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  5348,
                                                         z  =  2239,
                                                         zonename =  "Moonshade Highlands",
                                                         zoneid   =  zn2id["Moonshade Highlands"],
                                                      },
                                    },   -- 32
         ["Droughtlands"]        =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Mongo Vachir",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  9161,
                                                         z  =  6927,
                                                         zonename =  "Droughtlands",
                                                         zoneid   =  zn2id["Droughtlands"],
                                                      },
                                    },   -- 33
         ["Iron Pine Peak"]      =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Harwin Kalmar",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  4980,
                                                         z  =  1865,
                                                         zonename =  "Iron Pine Peak",
                                                         zoneid   =  zn2id["Iron Pine Peak"],
                                                      },
                                    },   -- 34
         ["Shimmersand"]         =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Qara Chuluun",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  7535,
                                                         z  =  7170,
                                                         zonename =  "Shimmersand",
                                                         zoneid   =  zn2id["Shimmersand"],
                                                      },
                                    },   -- 35
         ["Stillmoor"]           =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Cairn of Thera Valnir",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  1585,
                                                         z  =  1862,
                                                         zonename =  "Stillmoor",
                                                         zoneid   =  zn2id["Stillmoor"],
                                                      },
                                    },   -- 36
         ["Cape Jule"]        =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Ina'eme Sarus",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  7438,
                                                         z  =  12194,
                                                         zonename =  "Cape Jule",
                                                         zoneid   =  zn2id["Cape Jule"],
                                                      },
                                    },  -- 37
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Queny Sulgar",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  7765,
                                                         z  =  11041,
                                                         zonename =  "Cape Jule",
                                                         zoneid   =  zn2id["Cape Jule"],
                                                      },
                                    },  -- 38
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Asha Tonavar",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  6436,
                                                         z  =  11015,
                                                         zonename =  "Cape Jule",
                                                         zoneid   =  zn2id["Cape Jule"],
                                                      },
                                    },  -- 39
                                 },
         ["City Core"]        =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Nunmemph Batshinshi",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  7266,
                                                         z  =  9340,
                                                         zonename =  "City Core",
                                                         zoneid   =  zn2id["City Core"],
                                                      },
                                    },   -- 40
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Warsul Icero",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  7096,
                                                         z  =  8585,
                                                         zonename =  "City Core",
                                                         zoneid   =  zn2id["City Core"],
                                                      },
                                    },   -- 41
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Irque Guemech",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  7168,
                                                         z  =  8303,
                                                         zonename =  "City Core",
                                                         zoneid   =  zn2id["City Core"],
                                                      },
                                    },   -- 42
                                 },
         ["Eastern Holdings"] =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Oryp Namap",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  7534,
                                                         z  =  8879,
                                                         zonename =  "Eastern Holdings",
                                                         zoneid   =  zn2id["Eastern Holdings"],
                                                      },
                                    },   -- 43
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Tathon I'rilgar",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  8090,
                                                         z  =  9626,
                                                         zonename =  "Eastern Holdings",
                                                         zoneid   =  zn2id["Eastern Holdings"],
                                                      },
                                    },   -- 44
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Banald Warver",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  9096,
                                                         z  =  8384,
                                                         zonename =  "Eastern Holdings",
                                                         zoneid   =  zn2id["Eastern Holdings"],
                                                      },
                                    },   -- 45
                                 },
         ["Ardent Domain"]    =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Yer'shyi Att",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y  =  0,
                                                         x  =  5844,
                                                         z  =  9834,
                                                         zonename =  "Ardent Domain",
                                                         zoneid   =  zn2id["Ardent Domain"],
                                                      },
                                    },   -- 46
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Riduf Enthurn",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  4830,
                                                         z  =  10189,
                                                         zonename =  "Ardent Domain",
                                                         zoneid   =  zn2id["Ardent Domain"],
                                                      },
                                    },  -- 47
                                 },
         ["Kingsward"]        =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Niey Tiran",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  6231,
                                                         z  =  7240,
                                                         zonename =  "Kingsward",
                                                         zoneid   =  zn2id["Kingsward"],
                                                      },
                                    },   -- 48
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Isbur Oughverund",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  5601,
                                                         z  =  8070,
                                                         zonename =  "Kingsward",
                                                         zoneid   =  zn2id["Kingsward"],
                                                      },
                                    },   -- 49
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Skeltorard Perdyn",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  4066,
                                                         z  =  9072,
                                                         zonename =  "Kingsward",
                                                         zoneid   =  zn2id["Kingsward"],
                                                      },
                                    },   -- 50
                                 },
         ["Ashora"]           =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Okalu Prev",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  4063,
                                                         z  =  7123,
                                                         zonename =  "Ashora",
                                                         zoneid   =  zn2id["Ashora"],
                                                      },
                                    },   -- 51
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Omoosi Itnal",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  2678,
                                                         z  =  7117,
                                                         zonename =  "Ashora",
                                                         zoneid   =  zn2id["Ashora"],
                                                      },
                                    },   -- 52
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Orn Tonall",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=  0,
                                                         x  =  2083,
                                                         z  =  6035,
                                                         zonename =  "Ashora",
                                                         zoneid   =  zn2id["Ashora"],
                                                      },
                                    },   -- 53
                                 },
         ["The Dendrome"]     =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Morbur Atl Itther",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  2960,
                                                         z  =  4555,
                                                         zonename =  "The Dendrome",
                                                         zoneid   =  zn2id["The Dendrome"],
                                                      },
                                    },   -- 54
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Uomu Tonig",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=  0,
                                                         x  =  3988,
                                                         z  =  5925,
                                                         zonename =  "The Dendrome",
                                                         zoneid   =  zn2id["The Dendrome"],
                                                      },
                                    },   -- 55
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Ildbur Reled",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  4539,
                                                         z  =  4273,
                                                         zonename =  "The Dendrome",
                                                         zoneid   =  zn2id["The Dendrome"],
                                                      },
                                    },   -- 56
                                 },
         ["Kingdom of Pelladane"]= {{  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Omight Tonig",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  8484,
                                                         z  =  5896,
                                                         zonename =  "Kingdom of Pelladane",
                                                         zoneid   =  zn2id["Kingdom of Pelladane"],
                                                      },
                                    },   -- 57
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Tirror Awaya",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  7455,
                                                         z  =  4077,
                                                         zonename =  "Kingdom of Pelladane",
                                                         zoneid   =  zn2id["Kingdom of Pelladane"],
                                                      },
                                    },   -- 58
                                 },
         ["Seratos"]          =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Vesdar Doc",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  10593,
                                                         z  =  4800,
                                                         zonename =  "Kingdom of Pelladane",
                                                         zoneid   =  zn2id["Kingdom of Pelladane"],
                                                      },
                                    },   -- 59
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Sayiss Vernys",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  11257,
                                                         z  =  3610,
                                                         zonename =  "Seratos",
                                                         zoneid   =  zn2id["Seratos"],
                                                      },
                                    },   -- 60
                                 },
         ["Morban"]           =  {  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Osm",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  12333,
                                                         z  =  4715,
                                                         zonename =  "Morban",
                                                         zoneid   =  zn2id["Morban"],
                                                      },
                                    },   -- 61
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Urari Urari",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  12641,
                                                         z  =  7346,
                                                         zonename =  "Morban",
                                                         zoneid   =  zn2id["Morban"],
                                                      },
                                    },   -- 62
                                    {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Lunibe",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  15702,
                                                         z  =  6066,
                                                         zonename =  "Morban",
                                                         zoneid   =  zn2id["Morban"],
                                                      },
                                    },   -- 63
                                 },
         ["Steppes of Infinity"] =  {  idx         =  nil,
                                       text        =  nil,
                                       timestamp   =  os.time(),
                                       label       =  "Fevok Beleen",
                                       category	   =  "Cairns",
                                       playerpos   =  {  y	=   0,
                                                         x  =  15592,
                                                         z  =  7395,
                                                         zonename =  "Steppes of Infinity",
                                                         zoneid   =  zn2id["Steppes of Infinity"],
                                                      },
                                    },   -- 64
         }

   self.db  =  t

   return self
end
